# This workflow will run a test suite.

name: Run Tests
on:
  push:
  pull_request:
    branches:
      - master

defaults:
  run:
    shell: bash

jobs:
  call-linting:
    uses: voightp/github-actions/.github/workflows/run-linting.yml@main
    with:
      os: ubuntu-latest
      python-version: 3.9
  call-tests:
    uses: voightp/github-actions/.github/workflows/run-tests.yml@main
    with:
      pytest-args: "tests/test_db_temperature_distribution.py -v"
